export * as fdaMedicalDeviceIprSecurity from "./fda-medical-device-ipr-security.gai.ts";
export * as fdaMitreAttAndCkForEnterprise from "./fda-mitre-att-and-ck-for-enterprise.gai.ts";
export * as fdaMitreAttAndCkForMobile from "./fda-mitre-att-and-ck-for-mobile.gai.ts";
export * as fdaMitrePreAttAndCk from "./fda-mitre-pre-att-and-ck.gai.ts";
export * as medicalDeviceSecurityMds2 from "./medical-device-security-MDS2.gai.ts";
export * as medigyMedicalDeviceManagement from "./medigy-medical-device-management.gai.ts";
export * as medigySdlcHipaaPrivacyPharma from "./medigy-sdlc-hipaa-privacy-pharma.gai.ts";
export * as medigyTechnicalQuestionnaireForVendorHostedOfferings from "./medigy-technical-questionnaire-for-vendor-hosted-offerings.gai.ts";
export * as oncHipaaComplianceChecklistHealthIt from "./onc-hipaa-compliance-checklist-health-it.gai.ts";
export * as oncHipaaPrivacyPharma from "./onc-hipaa-privacy-pharma.gai.ts";
export * as oncHipaaSecurityPharma from "./onc-hipaa-security-pharma.gai.ts";
export * from "./information-assurance-facets.gai.ts";
